base_url: ''

exclude:
  - Readme.md
  - node_modules

defaults:
  - scope: {path: ''}
    values:
      layout: 'page'

  - scope: {path: '', type: 'instante'}
    values: {layout: 'instanta'}

  - scope: {path: '', type: 'parchete'}
    values: {layout: 'parchet'}
  
  - scope: {path: ''}
    values: {hasCrumbs: false}

collections:
  instante: {output: true}
  parchete: {output: true}

analytics: true
