base_url: '/onoratainstanta'
defaults:
  - scope: {path: ''}
    values:
      layout: 'page'

  - scope: {path: '', type: 'instante'}
    values: {layout: 'instanta'}

collections:
  instante: {output: true}

exclude:
  - build
