base_url: ''

exclude:
  - Readme.md

defaults:
  - scope: {path: ''}
    values:
      layout: 'page'

  - scope: {path: '', type: 'instante'}
    values: {layout: 'instanta'}

  - scope: {path: '', type: 'parchete'}
    values: {layout: 'parchet'}

collections:
  instante: {output: true}
  parchete: {output: true}

analytics: true
